from config import *

# app settings
SECRET_KEY = 'YOUR_SECRET_KEY_HERE'
USERNAME = 'YOUR_ADMIN_NAME'
PASSWORD = 'YOUR_ADMIN_PASSWORD'

# email settings
ADMINS = ['YOUR_MAILS_FROM_ADMINS']
MAIL_SERVER = 'YOUR_SERVER_NAME'
MAIL_PORT = 'PORT_INTEGER_NUMBER_AS_25_587_ETC'
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')

#### AMAZON SES SAMPLE ######
# MAIL_SERVER = 'email-smtp.us-east-1.amazonaws.com'
# MAIL_PORT = 587
# MAIL_USE_TLS = True
# MAIL_DEFAULT_SENDER = 'team@hipy.co'
# AWS_SES_RETURN_PATH = 'ADDRESS_TO_REPLY'
# AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID'
# AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY'

